In this moment the driver is mostly working
Tests can run using:

    ./django/tests/runtests.py --settings=configs.test_psycopg3 \
        -v2 --keepdb --noinput --parallel=1 2>&1 \
    | tee pg3-$(date -Isec --utc).log

The result at the moment is:

    FAILED (failures=1, errors=14, skipped=763, expected failures=7)
    Ran 14748 tests in 458.192s

The errors remaining are:

```
======================================================================
ERROR: test_bulk_update (postgres_tests.test_bulk_update.BulkSaveTests) (model=<class 'postgres_tests.models.HStoreModel'>, field='field')
ERROR: test_array_field (postgres_tests.test_hstore.SimpleTests)
ERROR: test_key_val_cast_to_string (postgres_tests.test_hstore.SimpleTests)
ERROR: test_save_load_success (postgres_tests.test_hstore.SimpleTests)
ERROR: test_value_null (postgres_tests.test_hstore.SimpleTests)
ERROR: setUpClass (postgres_tests.test_hstore.TestQuerying)
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
django.db.utils.ProgrammingError: cannot adapt type dict to format AUTO

======================================================================
ERROR: test_bulk_update (postgres_tests.test_bulk_update.BulkSaveTests) (model=<class 'postgres_tests.models.RangesModel'>, field='ints')
ERROR: test_bulk_update (postgres_tests.test_bulk_update.BulkSaveTests) (model=<class 'postgres_tests.models.RangesModel'>, field='dates')
ERROR: test_bulk_update (postgres_tests.test_bulk_update.BulkSaveTests) (model=<class 'postgres_tests.models.OtherTypesArrayModel'>, field='ips')
ERROR: test_bulk_update (postgres_tests.test_bulk_update.BulkSaveTests) (model=<class 'postgres_tests.models.OtherTypesArrayModel'>, field='json')
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

======================================================================
ERROR: test_nodb_cursor_reraise_exceptions (backends.postgresql.tests.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
RuntimeWarning: Normally Django will use a connection to the 'postgres' database to avoid running initialization queries against the production database when it's not needed (for example, when running tests). Django was unable to create a connection to the 'postgres' database and will use the first PostgreSQL database instead.

======================================================================
ERROR: test_extract_func_with_timezone_minus_no_offset (db_functions.datetime.test_extract_trunc.DateFunctionWithTimeZoneTests) [backports.zoneinfo.ZoneInfo(key='Asia/Ust-Nera')]
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
django.db.utils.DataError: time zone "Asia/Ust+Nera" not recognized

======================================================================
ERROR: test_extract_func_with_timezone_minus_no_offset (db_functions.datetime.test_extract_trunc.DateFunctionWithTimeZoneTests) [<DstTzInfo 'Asia/Ust-Nera' LMT+9:33:00 STD>]
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block

======================================================================
ERROR: test_create_test_db (backends.postgresql.test_creation.DatabaseCreationTests)
----------------------------------------------------------------------
django.db.utils.DatabaseError: database "test_test_piro" already exists

======================================================================
FAIL: test_sql_table_creation_raises_with_collation (backends.postgresql.test_creation.DatabaseCreationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
AssertionError: PostgreSQL does not support collation setting at database creation time.
```